### ISSUE TITLE
plugin freeze issues, probably when backend is slow

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#1020]
STR
connect to Meloona  and edit the document

**Comment by shalom938** [comment]
@shaykeren @asafchen-dig @doppleware 
It appears that the freeze is causes because the summary view loads a long list and the swing rendering takes a long time.
a quick fix is to limit the list to 20. a long term fix is to implement some kind of pagination.

this PR limits the list to 20
https://github.com/digma-ai/digma-intellij-plugin/pull/1030
