### ISSUE TITLE
OpenLiberty support

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#1090]
1. Don't run the agent for OpenLiberty/Microprofiler projects
2. Need to set otel.exporter.otlp.endpoint=http://localhost:5050/ in microprofile-config.properties
3. Right now for the sample project we still don't have it functioning:
    a. If we click an endpoint it does not identify the right code location
    b. If we navigate to that location we do recognize endpoint and span
    c. @withspan annotations are working (including navigations) but don't show up as link in the Jaeger view

**Comment by arik-dig** [comment]
questions
A) reg 2, editing config file is too intrusive isn't it? lets try to find another way such as SystemProperty or Environment Variable
B) reg 3a - it relates to existing issue https://github.com/digma-ai/digma-intellij-plugin/issues/1039
C) reg 3c - jaeger navigation doesn't work since MicroProfile won't set `code.function` and `code.namespace` for @WithSpan - hence digma backend doesn't have it

**Comment by arik-dig** [comment]
the jaeger links has a bug, see PR #1092 - which fixes it
