### ISSUE TITLE
micronaut - Support micronaut client side discovery

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#1581]
See annotation:
<img width="744" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjIzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ea24a70b0db803149a6a2391ca8bfa7f0253fef/image.png" alt="image.png" />

**Comment by shalom938** [comment]
The issue with discovery for micronaut framework is:
from Arik's memory there was a bug in micronaut tracing that they added GET GET to the endpoint id and our discovery did the same. probably they fixed it and now our client discovery doesn't match. 
this branch fixes it for newer versions of micronaut
https://github.com/digma-ai/digma-intellij-plugin/tree/micronout-discovery
but in a way that will stop working for versions with the bug.
to support all version we need to create two endpoint each with relevant id matching micronaut with and without the bug.

@doppleware you can use the above branch to check if it fixes your issue at least.


more then that we have the following bugs with micronaut:
1) we support running micronaut app from the play button or context menu in idea. but micronaut have a gradle plugin that uses the java application plugin, when running the app from gradle we add the agent because we have no knowledge of the module and can't decide if its a micronaut module. so running the app from gradle plugin will not produce tracing.
2) we don't support micronaut maven plugin.

3) otel complains about missing -Dotel.java.global-autoconfigure.enabled=true, we need to add it to JAVA_TOOL_OPTIONS but try to understand when , for all frameworks or just for some?




I added some micronaut samples here
https://github.com/digma-ai/micronaut-samples
the gradle java and kotlin work and have tracing. need to add tracing to the maven kotlin/java

**Comment by shalom938** [comment]
this issue is related
https://github.com/digma-ai/digma-intellij-plugin/issues/1587

**Comment by doppleware** [comment]
First, the Micronaut version the customer is using is old (3.8.6)
I can check if the issue is the GET GET but the problem happens for the customer.

**Comment by shalom938** [comment]
related issue
https://github.com/digma-ai/digma-intellij-plugin/issues/1589
