### ISSUE TITLE
Refresh insights automatically

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#247]
Insights should refresh automatically. 
We should leave the refresh button (as a placebo) but Digma should no longer require user to move between functions or click it to show new information.
Consider refreshing the currently opened insight (the one active in the side pane) more frequently.

Phase 2 of this task (request from Shay):
In the context of this task please find a better way not to refresh all the opened document when user clicks on refresh or changing environment. we need to do it lazy.

**Comment by MykolaYaremchuk** [comment]
* implemented automatic refresh
* fixed UI freeze in initial load of Digma (fixed reload of summaries panel)


Automatic refresh is being executed each 10 seconds ONLY for active file.

Automatic refresh was implemented with help of` Kotlin Coroutines` and `lifetime`s (because Java background thread are heavy).
We create a `lifetime` for actual focused file
Lifetime by itself is a lightweight and heavily optimized object. It is okay to create new lifetime on each selection change without any performance impact whatsoever.  (Consulted with Jetbrains developer).

`LIFETIME` is more or less simple class (https://github.com/JetBrains/rd/blob/ec794823a473e7abff65d969cb70e70ade9ec057/rd-kt/rd-core/src/main/kotlin/com/jetbrains/rd/util/lifetime/RLifetime.kt) that allows to collect actions and then execute them on lifetime termination. You may conceptually assign a lifetime to anything, and perform operations on said lifetime (attach stuff to it, and expect it to be executed when the lifetime terminates).
Some of objects in Rider already have their assigned lifetimes (such as `project.lifetime` or some `LifetimedService.lifetime`).


So in scope of this task `lifetime` was use to execute `refreshAllForCurrentFile` **_Coroutine task_**.
