### ISSUE TITLE
error while upgrading the plugin

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#258]
Error details:

The IDE failed to install or update some plugins.
Please try again, and if the problem persists, please report it
to https://jb.gg/ide/critical-startup-errors

The cause: java.nio.file.AccessDeniedException: C:\Users\tomer.v\AppData\Roaming\JetBrains\Rider2022.2\plugins\digma-intellij\dotnet\Digma.Rider.dll

STR

(Windows machine)
1. having a new version of the plugin
2. upgrade the plugin and restart IDEA
3. observe the following error after the Idea was closed

Workaround 

uninstall and install the plugin.

**Comment by MykolaYaremchuk** [comment]
<img width="554" alt="image" src="https://user-images.githubusercontent.com/117861250/211511010-9855c609-4322-4043-bbd5-7dedc6a4687d.png">
screenshot from Roni

**Comment by MykolaYaremchuk** [comment]
Conclusion after chatting with Jetbrains Ridder platform developer:
"It's a known Rider problem [RIDER-65562](https://youtrack.jetbrains.com/issue/RIDER-65562).
No resolution other than just restart again."

The only thing we can do is to mark <idea-plugin require-restart="true"> inside plugin.xml - but we already have this configured in our plugin.xml.

This issue should be fixed in scope of 2023.2 Rider release.
