### ISSUE TITLE
auto refresh changing UI issues

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#281]
Issues:
1. scrollbar changes its position 
2. on insights with paging, the page is not preserved between refresh
3. The refreshed label at the bottom toolbar is flickering all the time, we should remove it is annoying 
4. sometimes an exception is raised  while clicking the refresh button

**Comment by MykolaYaremchuk** [comment]
Issue #2 was fixed in scope of release `v2.0.21` (`v1.0.72`) :
What's Changed:
* Fix for DurationBreakdown insight to keep correct active page after automatic refresh

Issue #3 was fixed in scope of release `v2.0.19` (`v1.0.70`):
What's Changed:
* change background task to lifetime task to avoid flickering of bottom

**Comment by MykolaYaremchuk** [comment]
All issues are fixed in scope of v2.0.22

**Comment by MykolaYaremchuk** [comment]
issue 1 will be fixed is scope of https://github.com/digma-ai/digma-intellij-plugin/issues/323
