### ISSUE TITLE
Design our strategy for allowing quick instrumentation of Java code via Maven/Gradle

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#306]
We need to accomplish the following with minimal friction:
1. Download OTEL agent
2. (Optional) Download Digma OTEL extension
3. Add these to .gitignore (for now)
4. Add VM options to include the agent in runtime. (maybe we can add it as a toggle in our plugin panel so if enabled it will always inject the VM options when running to the current config)

Research, whether we need/, should use Gradle/Maven plugins and what they offer.
Add hamburger Icon and menu item with the toggle button see screenshot
![image.png](https://images.zenhubusercontent.com/629081fe8e8390586a69e972/9be16d0f-a46c-4519-a111-fac123ca7d08)

**Comment by arik-dig** [comment]
After discussion with Shay, we figured out few things:

1. We assume that we want to automate the manual stuff done in this guide : https://digma.ai/java-quick-start-guide/
2. The download of Agent (+Digma extension) could be part of the plugin itself, and it will store it in some common or temp location
3. Currently we can adjust "RunConfigs" and adding the definitions of agent and extension to either:
a) ALL run configs - I think this option is too intrusive, and developers won't like it
b) Let the user choose from his existing "run configs"
4. Other option is to research a way of creating our own "RunConfig" similar to Java Run Config and wrap it with the needed agent parameters and system settings

**Comment by doppleware** [comment]
I want us to consider the feasibility of adding a toggle button, for example on the recent activity panel or plugin panel.
Whenever the toggle is on, the agent parameters would be injected.

**Comment by doppleware** [comment]
We can use this env variable to enable the agent:
ENV JAVA_TOOL_OPTIONS=-javaagent:/opt/opentelemetry-agent.jar

**Comment by shaykeren** [comment]
@arik-dig  please add the list of environment variable and their values that need to be set

**Comment by arik-dig** [comment]
In addition to JAVA_TOOL_OPTIONS we need the following system properties to be set:

 -Dotel.javaagent.extensions=digma-otel-agent-extension.jar
 -Dotel.traces.exporter=otlp
 -Dotel.exporter.otlp.traces.endpoint=http://localhost:5050

note that exporter URL might be needed to have configuration

**Comment by shalom938** [comment]
@arik-dig @doppleware @shaykeren 

My plan is to add JAVA_TOOL_OPTIONS that will contain all digma arguments, for example:
JAVA_TOOL_OPTIONS="-javaagent:/opt/opentelemetry-agent.jar -Dotel.javaagent.extensions=digma-otel-agent-extension.jar -Dotel.traces.exporter=otlp -Dotel.exporter.otlp.traces.endpoint=http://localhost:5050/"

it is possible to just add those to the java command line without an environment variable.

Some questions:

1. currently what i see is that if i add that to run configuration it is persisted in the run configuration settings, it means that if the toggle is not ON then i need to remove. it also means that if the run configuration is shared through vcs other users will get it. I will try to find a way to do it without saving to the run configuration but currently that's what the intellij API does.
2. what to do in the rare case that the user already has JAVA_TOOL_OPTIONS for his own needs, add digma stuff to it ?
3. on which run configuration types we want to add digma stuff ? there are many types, for example: java application which is a run configuration for a main method, gradle run configuration, maven, tomcat , unit tests, and there are many more types.
4. where to save the downloaded jars ? the easiest is java.io.tmpdir, maybe there is also a possibility to user cache or intellij cache directory. downloads may occur more then once because these directories may be deleted or emptied.

**Comment by doppleware** [comment]
1. If we can avoid changing the file that's great otherwise, we'll suffer the fact that the file is changed.
2. We don't want to replace variables that already exist
3. All run configurations - the env variables should not do harm. However please note that what we are suggesting is that the run config is NOT modified when you click the button (toggle to ON). When you click run it will check the status of the toggle and inject the env variables then. When you click stop, it will restore to what it was.
4.  java.io.tmpdir is fine.

**Comment by doppleware** [comment]
Additional topics:
* For the service name (OTEL_SERVICE_NAME): we want to use the runtime config name. Of course, if the user set it to a different value, we won't override it.
* The Digma host name should be taken from the settings (default to localhost) (OTEL_TRACES_ENDPOINT)

**Comment by arik-dig** [comment]
@doppleware , @shaykeren ,

Feature support: I think we need to have setting for destination of OTLP exporter (the default would be localhost:5050), but I think we should leave a way to modify it so user could redirect his traces to somewhere else - centralized place, or for us in digma, to modify to 4317 so we could see the traces as well via jaeger.

**Comment by shaykeren** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Digma-Team-629081e5a37b4b0015ac6813/issues/digma-ai/digma-intellij-plugin/306?planning-poker) with Zenhub @arik-dig @asafchen-dig @borisermakof @kshmidt-digma @MykolaYaremchuk

**Comment by shalom938** [comment]
@doppleware 
you said to add to all run configuration, there are many types, currently my question is, are you sure you want to interfere will all unit tests? and when debugging? and there are many other types like tomcat runner, application server runner, gradle that just runs some gradle task that is not running an application,it can be any gradle task.

**Comment by shalom938** [comment]
The humburger button is installed only on idea, the decision is made based on if the JavaLanguageService is registered.

There is no easy way to know if a project is a java project. intellij doesn't have a project type. intellij projects
have modules and each module has some nature. there may be a project that contains a java module and python module,  so it's not a java project and not a python project.
it is possible to query the project modules and make some heuristics and decide if it's a java project if most of the modules are java.
currently what we test is if the JavaLanguageService is registered, that is good enough to decide if its idea because the java plugin is installed only on idea and can not be installed on other IDEs.
python plugin can be installed on some IDEs and so if the PythonLanguageService is registered that doesn't necessarily mean that its pycharm.
that means if python plugin is installed on idea then the hamburger icon will be installed also for python projects. to improve that we need to query the project modules.

the implementation is in IDEUtilsService

**Comment by shalom938** [comment]
A summary of how this feature works:
the extension implementing the feature is AutoOtelAgentRunConfigurationExtension

The extensions injects JAVA_TOOL_OPTIONS environment variable containing otel agent jar to certain run configuration types.

Note that there is no check is the run configuration already contains otel agent, if it does it will be added twice which is probably not ideal.

the feature can be enabled/disabled by a toggle button
![image](https://user-images.githubusercontent.com/170266/226208669-83ea2405-6be1-481d-a6fe-b8d51376269a.png)

currently the toggle button is installed only on idea. see comment above about that issue and how to improve identifying the type of the project.

Jars download:
the otel and digma extension jars are downloaded on IDE start and deleted on IDE shutdown. they are saved in tmp directory.  they will be re-downloaded on run configuration execution in case they were deleted while the IDE is up.

what's injected:
-javaagent:/path to oter agent
-Dotel.javaagent.extensions=path to fidma extension jar
-Dotel.traces.exporter=otlp
-Dotel.metrics.exporter=none
-Dotel.exporter.otlp.traces.endpoint= digma url: take the host from the plugin settings and build http://$host:5050
-Dotel.service.name=service name: if possible take the java module name, if not, the project name. remove spaces. 

for example:
Picked up JAVA_TOOL_OPTIONS: -javaagent:/tmp/digma-otel-jars2/opentelemetry-javaagent.jar -Dotel.javaagent.extensions=/tmp/digma-otel-jars2/digma-otel-agent-extension.jar -Dotel.traces.exporter=otlp -Dotel.metrics.exporter=none -Dotel.exporter.otlp.traces.endpoint=http://192.168.122.74:5050 -Dotel.service.name=spring-petclinic-otel-with-digma-agent


If the run configuration already has JAVA_TOOL_OPTIONS its merged with ours.
quick instrumentation 

Supported run configuration types:

there is a settings in Idea to choose to run applications and unit tests with gradle or with intellij, its in the gradle settings.
with intellij means running the java command for apps or junit runner for unit tests.  
with gradle means running the app with gradle, for a main method the gradle plugin will generate a gradle scripts in place with a task called MyClass.main and a javaExec task to execute it and will execute the task.
for unit tests gradle will run the ':test' task.
its also possible to run app or unit tests with maven.
and there is also a JarApplicationConfiguration to execute a jar with java -jar.

The extension supports the following run configurations:

java run configurations:
ApplicationConfiguration, JUnitConfiguration, TestNGConfiguration, KotlinRunConfiguration,
KotlinStandaloneScriptRunConfiguration, GroovyScriptRunConfiguration, JarApplicationConfiguration

Gradle run configurations:
we can decide to inject the agent only by gradle task names. 
when gradle executes a task it forks a jvm,The only way in gradle is to inject JAVA_TOOL_OPTIONS, that will cause gradle itself to also pickup this env and run with otel agent. and then the forked jvm will pickup this env too. i didn't see any issue with that so i guess its ok.
for gradle run configuration the JAVA_TOOL_OPTIONS is added to the settings before execution, that was the easiest way. it is saved in the settings, but there is a listener that cleans it when the process is terminated. it will be cleaned when the process is terminated gracefully or when idea is shutdown, if idea will crash it will not be cleaned. 
we support:
a gradle task that contains '.main'  for example 'MyClass.main', assuming its an auto generated task and not a user task that happens to contain that in its name.
the ':test' task, for all unit tests or single unit test. also for inner modules like ':myModule:test'.
the ':bootRun' task, also for inner modules like ':myModule:bootRun'.
This is not perfect, a user can define a gradle task named myTask of type JavaExec and execute a java app. we don't know the type of the tasks, only names, discovering the type of the task requires digging into the gradle script. same with test, a user can define a task named myTests of type Test.
all other gradle tasks are ignored.

Maven run configuration.
maven can run a java app with the exec plugin and unit tests with surefire plugin.
with maven and JAVA_TOOL_OPTIONS there is the same issue as with gradle, maven itself with pickup this env and run with the otel agent and the forked jvm too.
we support:
maven goal 'spring-boot:run'
maven goal 'exec:java'
maven goal 'exec:exec -Dexec.executable=java'
maven goal 'surefire:test'
all other goals are ignored
