### ISSUE TITLE
Rider is not responding

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-intellij-plugin#311]
STR
While working on some document
The idea was not responding while Digma:AnalyzeDocument was running for a long time around some minutes.
please note that I had around 15 documents opened

[ShayK]  I can send my Rider logs..

**Comment by MykolaYaremchuk** [comment]
Please send your Rider logs, it will help me to understand on which process AWT thread was freezing the UI

**Comment by MykolaYaremchuk** [comment]
After investigation of logs from Shay's machine I figured out that root cause of this problem was `DocumentInfoService`:
`    private final Map<String, DocumentInfoContainer> documents = Collections.synchronizedMap(new HashMap<>());`

The thread calling the `removeDocumentInfo` method was blocked waiting to acquire the lock of the `synchronized` map.

To improve this, I used a concurrent map implementation (`ConcurrentHashMap`) instead of a `synchronized` map. This will allow multiple threads to access the map concurrently without blocking each other.

By using `ConcurrentHashMap`, we can avoid blocking the UI thread and improve the concurrency of our application.
