### ISSUE TITLE
Support instrumenting run config via Quarkus plugin

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#922]

**Comment by arik-dig** [comment]
Quarkus Plugin source : 
[https://github.com/redhat-developer/intellij-quarkus](https://github.com/redhat-developer/intellij-quarkus)

**Comment by arik-dig** [comment]
after investigating and debugging, seems like we ALREADY trapping the quarkus RunConfig type, since they are just wrappers for Maven RunConfig - which is already handled by us.

see the screen shots

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/f89f4fa7-4287-400c-9fd2-364734ba56ac)

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/bf80060a-ff70-481e-871a-e6d760fa6da8)

**Comment by arik-dig** [comment]
did nothing - it works for [Quarkus Tools](https://plugins.jetbrains.com/plugin/13234-quarkus-tools)
